### ISSUE TITLE
Please add Dutch as a language

### ISSUE THREAD

**Issue by iFloris** [pluja/web-whisper#1]
Hello, this looks super cool! I would like for try it, but nearly all my audio is in Dutch. Would it be possible to add the Dutch language or is this something that I as a user can do myself?

**Comment by pluja** [comment]
Added! Pull the last changes and you will be able to use it.

**Comment by iFloris** [comment]
> Added! Pull the last changes and you will be able to use it.

Thanks a lot! Will give it another go 😀
