### ISSUE TITLE
mimeType is not supported when using Safari

### ISSUE THREAD

**Issue by ggerganov** [pluja/web-whisper#2]
Hi, I tried using the demo server in Safari and got the following error:

![image](https://user-images.githubusercontent.com/1991296/204344762-ec276ae3-d8cf-4686-8d4e-afa4be532777.png)

At this point, the "Stop" button does nothing - it generates more errors in the console.
It works with Chrome.

Also, I think in general it is a good practice to make the web page to first require the user to make some action (like press a button) and after that ask for the microphone permission. I cannot find a reference, but I think if you don't do it like that, then some browsers will not allow mic access due to security reasons.

**Comment by pluja** [comment]
Hey, thanks a lot for your feedback. I will implement a button to trigger the microphone request to see if it can solve the Safari issue.

I don't own any Apple device so it is difficult for me to test it.

PS: Thanks for developing whisper.cpp :)

**Comment by pluja** [comment]
This should now be solved with the latest changes :)

See: https://codeberg.org/pluja/web-whisper/pulls/12
