### ISSUE TITLE
Possible to disable Record button?

### ISSUE THREAD

**Issue by aaaaaammmmmm** [pluja/web-whisper#3]
Hi, 
Is there an easy way to disable and remove the Record button and the error messages when mic is not available if you only want to use the File upload function? 

Thanks!

**Comment by pluja** [comment]
Right now there is no way to do that. But I can add an option to disable it.

**Comment by pluja** [comment]
Since version v1.2.3, if you don't push the “record” button, no errors should appear and no permissions are asked. 

I'm closing this issue, as it does not make much sense to me to disable recording and enabling uploading files and this should no longer be a problem if you update.
