### ISSUE TITLE
Expanding language with Polish

### ISSUE THREAD

**Issue by ChmurnikX** [pluja/web-whisper#4]
Hi is it possible, and if how to expand languages with Polish language?

**Comment by pluja** [comment]
Yes! Will add it tomorrow as soon as I can!

**Comment by an303042** [comment]
Could you also add Arabic and Hebrew please?

**Comment by pluja** [comment]
Just added Polish (@ChmurnikX) along with Hebrew (@an303042).

Also Portuguese, Finnish, Swedish were added. 
 
@an303042  Please note that the WER (Word Error Rate) on Hebrew is considerably bigger than other languages:

![](https://github.com/openai/whisper/raw/main/language-breakdown.svg)
