### ISSUE TITLE
Download later option? - Suggestion

### ISSUE THREAD

**Issue by getjake** [pluja/web-whisper#6]
Because it always takes a while to generate the transcripts, the browser window may be closed accidentally. It is possible to let use r submit their task with the task ID; and download the transcripts later using the ID on the interface?

**Comment by pluja** [comment]
Good idea. I will work on it after vacation!

**Comment by pluja** [comment]
This has now been added in the latest version: https://codeberg.org/pluja/web-whisper/releases/tag/v1.4

For now, you can only access the files from the filesystem. I will add a frontend for this feature in a future release.
