### ISSUE TITLE
Swiss German?

### ISSUE THREAD

**Issue by ninoppp** [pluja/web-whisper#8]
Hey there

I'd absolutely love to use this prject (looks great) but I'd need support for Swiss German (which Whisper has). This isn't implemented yet afaik? would that be possible?

**Comment by pluja** [comment]
Added with the latest commit!

https://codeberg.org/pluja/web-whisper/commit/6514430e1177c829fcf7cc9b3e2e5c1894e23b3d

**Comment by ninoppp** [comment]
thanks!
